name: Movies
form: $/watchlearn/movies/models/detail/fields.yaml
modelClass: Watchlearn\Movies\Models\Detail
defaultRedirect: watchlearn/movies/movies
create:
    redirect: 'watchlearn/movies/movies/update/:id'
    redirectClose: watchlearn/movies/movies
update:
    redirect: watchlearn/movies/movies
    redirectClose: watchlearn/movies/movies
