list: $/watchlearn/movies/models/detail/columns.yaml
modelClass: Watchlearn\Movies\Models\Detail
title: Movies
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'watchlearn/movies/movies/update/:id'
